### ISSUE TITLE
IPs read in from File Targets do not work due to newlines not being stripped

### ISSUE THREAD

**Issue by jsherwood0** [byt3bl33d3r/CrackMapExec#365] opened 2020-05-02 09:05 UTC
**Describe the bug**
IPs read in from File Targets do not work due to newlines not being stripped.

**To Reproduce**
1. Create a text file (e.g., hosts.in) with one IP address per line
2. cme --verbose smb hosts.in
3. Note that IP addresses are not recognized and appear to have newlines included at the end of each

**Expected behavior**
Each line should have whitespace stripped and be parsed properly as an IP address.

**Screenshots**
N/A

**Crackmapexec info**
 - OS: Kali Rolling 2020.1
 - Version of CME: 5.0.1.dev1+20200502.13819.17d06f9
 - Installed from latest git repo with my version commit included

**Additional context**
N/A

**Comment by mpgn** [comment] 2020-05-02 09:46
Hello, duplicate of #352 

Code in the dev branch will be merged end of the week

**Closed by mpgn** 2020-05-02 09:46 UTC
