### ISSUE TITLE
CME won't launch

### ISSUE THREAD

**Issue by sxplitfirex** [byt3bl33d3r/CrackMapExec#358] opened 2020-04-29 23:00 UTC
**Describe the bug**
crackmapexec won't start.
downloaded the latest version via apt, for some reason its throwing the below error.
I'm running kali and its fully updated

normally attempt to run the tool

**Screenshots**
```
root@kali:~/Desktop/CTF# crackmapexec 
Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 11, in <module>
    load_entry_point('crackmapexec==5.0.1.dev0', 'console_scripts', 'crackmapexec')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.1.dev0-py3.8.egg/cme/__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/crackmapexec-5.0.1.dev0-py3.8.egg/cme/thirdparty'
```

**Crackmapexec info**
 - OS: kali
 - Version of CME v5.0.1 dev

**Additional context**

**Comment by mpgn** [comment] 2020-04-30 09:09
Try using the lastest release https://github.com/byt3bl33d3r/CrackMapExec/releases

**Comment by mpgn** [comment] 2020-04-30 09:09
Closing since duplicate of #355

**Closed by mpgn** 2020-04-30 09:09 UTC
