### ISSUE TITLE
configparser.NoSectionError: No section: 'BloodHound'

### ISSUE THREAD

**Issue by barakagb** [byt3bl33d3r/CrackMapExec#527] opened 2022-02-01 15:04 UTC
**Describe the bug**
Getting error : configparser.NoSectionError: No section: 'BloodHound'
when using cme version greater 5.1.9 on smb | ldap 

**To Reproduce**
1. cme smb| ldap -u '<user>' -p '<pass>' IP
2. See error

**Expected behavior**
see login attempt status

**Screenshots**

**Crackmapexec info**
 - OS: Kali
 - Version of CME  greater thatn 5.1.9
 - Installed from apt and pipx

**Additional context**
Traceback (most recent call last):
  File "/home/cyber/.local/bin/cme", line 8, in <module>
    sys.exit(main())
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/crackmapexec.py", line 254, in main
    asyncio.run(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/crackmapexec.py", line 102, in start_threadpool
    await asyncio.gather(*jobs)
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/crackmapexec.py", line 68, in run_protocol
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/protocols/smb.py", line 125, in __init__
    connection.__init__(self, args, db, host)
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/connection.py", line 62, in __init__
    self.proto_flow()
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/connection.py", line 98, in proto_flow
    if self.login() or (self.username == '' and self.password == ''):
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/connection.py", line 275, in login
    if self.plaintext_login(self.domain, user, password): return True
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/protocols/smb.py", line 366, in plaintext_login
    add_user_bh(self.username, self.domain, self.logger, self.config)
  File "/home/cyber/.local/pipx/venvs/crackmapexec/lib/python3.9/site-packages/cme/helpers/bloodhound.py", line 7, in add_user_bh
    if config.get('BloodHound', 'bh_enabled') != "False":
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'BloodHound'

**Comment by xenophil90** [comment] 2022-02-01 18:59
Same problem.

**Comment by mpgn** [comment] 2022-02-01 19:52
Duplicate of #519

**Closed by mpgn** 2022-02-01 19:52 UTC
