### ISSUE TITLE
Some greenlet error

### ISSUE THREAD

**Issue by DanMcInerney** [byt3bl33d3r/CrackMapExec#17] opened 2015-10-18 23:05 UTC
Ran the script with:

./crackmapexec.py -t 25 some-ips.txt -d localhost -u username -p password --execm wmi -X "Import-Module ActiveDirectory; Get-ADGroup"

And just after a few successful login messages but prior to getting any output from the command, this error popped up:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 540, in __bootstrap_inner
    del _limbo[self]
KeyError: <_Timer(Thread-1, stopped daemon 59241488)>
<Greenlet at 0x387f410: <bound method _Timer.__bootstrap of <_Timer(Thread-1, stopped daemon 59241488)>>> failed with KeyError

Script just plowed on. It happened twice, then when I ran it a third time it went away. I have no idea what's causing so this is probably unhelpful but in case you run into it in the future maybe something here will be useful.

**Comment by byt3bl33d3r** [comment] 2015-10-18 23:29
Weird will try to reproduce this as well, although it seems to be a problem with gevent

**Comment by its0x08** [comment] 2015-11-11 17:18
It dosen happen to me .. 
you should do a git pull ;) 
i think now its fixed 
also .. pip install --upgrade -r requirements.txt

**Comment by byt3bl33d3r** [comment] 2016-03-27 21:33
Closing since I can't reproduce this at all

**Closed by byt3bl33d3r** 2016-03-27 21:33 UTC
Labels: bug, unable to reproduce
