### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by theoneandonly-vector** [byt3bl33d3r/CrackMapExec#11] opened 2015-09-29 22:18 UTC
Error Code:
/CrackMapExec-master/crackmapexec.py  -h
Traceback (most recent call last):
  File "/root/Desktop/Link to opt/CrackMapExec-master/crackmapexec.py", line 16, in <module>
    from impacket.dcerpc.v5 import transport, scmr, samr, drsuapi, rrp, tsch, srvs, wkst, epm
ImportError: cannot import name drsuapi

**Comment by theoneandonly-vector** [comment] 2015-09-29 22:18
System: Kali Linux 2.0 x64

**Comment by byt3bl33d3r** [comment] 2015-09-29 23:11
duplicate of #1 you have to update your impacket installation

**Closed by byt3bl33d3r** 2015-09-29 23:11 UTC
Labels: duplicate

**Comment by theoneandonly-vector** [comment] 2015-10-01 16:25
I already did that.. the problem was:
some of the packages were at a false location..
If somebody else has this issue, just run:
cp -R /usr/local/lib/python2.7/dist-packages/impacket /usr/lib/python2.7/dist-packages/
