### ISSUE TITLE
Cannot launch it in Kali 2.0 64-bit

### ISSUE THREAD

**Issue by jaredbarez** [byt3bl33d3r/CrackMapExec#2] opened 2015-08-19 20:48 UTC
![untitled](https://cloud.githubusercontent.com/assets/13761356/9368585/696f7bb4-46c4-11e5-9ea3-688085f506a8.png)

**Comment by byt3bl33d3r** [comment] 2015-08-19 20:52
@jaredbarez duplicate of #1

**Closed by byt3bl33d3r** 2015-08-19 20:52 UTC

**Comment by jaredbarez** [comment] 2015-08-19 20:55
eh. my fault. sorry
