### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pr4jwal** [byt3bl33d3r/CrackMapExec#3] opened 2015-08-19 21:12 UTC
```python
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "crackmapexec.py", line 1766, in connect
    smb.login('' , '')
<<redacted>>
<Greenlet at 0x1047b1190: connect('<<x.x.x.x>>')> failed with error
```
needs to handle the exception may be ?

**Comment by byt3bl33d3r** [comment] 2015-08-19 21:34
@pr4jwal I need the original traceback without redactions to understand whats going on :P 
also any exception from that function call is handled https://github.com/byt3bl33d3r/CrackMapExec/blob/master/crackmapexec.py#L1766

**Comment by byt3bl33d3r** [comment] 2015-08-20 09:00
@pr4jwal I'm closing this since, I can't reproduce this in any way.. feel free to comment below

**Closed by byt3bl33d3r** 2015-08-20 09:00 UTC
