### ISSUE TITLE
Error while starting crackmapexec

### ISSUE THREAD

**Issue by purabparihar** [byt3bl33d3r/CrackMapExec#383] opened 2020-05-21 14:41 UTC
When i type crackmapexec in my kali linux terminal then it returns this error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (asn1crypto 0.24.0 (/usr/lib/python3/dist-packages), Requirement.parse('asn1crypto>=1.3.0'), {'minikerberos'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/crackmapexec", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (asn1crypto 0.24.0 (/usr/lib/python3/dist-packages), Requirement.parse('asn1crypto>=1.3.0'), {'minikerberos'})

**Comment by mpgn** [comment] 2020-05-21 16:53
`pip3 install asn1crypto --upgrade --user`

**Comment by dhd0004** [comment] 2020-05-25 18:56
still having this issue

**Comment by mpgn** [comment] 2020-05-25 19:48
Probably duplicate of #377 

https://github.com/byt3bl33d3r/CrackMapExec/issues/377#issuecomment-633132568

**Closed by mpgn** 2020-05-25 19:48 UTC
