### ISSUE TITLE
Still some encoding issues

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#28] opened 2015-11-01 13:53 UTC
Hello @byt3bl33d3r,

I would like to report (again) some **encoding issues**.
Steps to reproduce:
1. Create a file named `àâæçéèêëïîôœ—– »« ”’€ÿüûù.txt` on a share. Note that this contains **french accents**.
2. List that share
3. See the bug
```
$ python crackmapexec.py -d adyolo -u user1 -p "yoloswag1!" 192.168.11.136 -s share --list encoding2
[*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:adyolo)
[+] 192.168.11.136:445 Login successful adyolo\user1:yoloswag1!
[+] 192.168.11.136:445 Contents of encoding2\*:
drw-rw-rw-       0 2015-11-01 22:50 .
drw-rw-rw-       0 2015-11-01 22:50 ..
-rw-rw-rw-      25 2015-11-01 22:32 credz.txt
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "crackmapexec.py", line 2903, in connect
    f.get_longname()))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-13: ordinal not in range(128)
<Greenlet at 0xb679bbbcL: connect('192.168.11.136')> failed with UnicodeEncodeError
```

I managed to fix this by editing the line #2093 
from:
```
f.get_longname()
```
to:
```
f.get_longname().encode('utf-8')
```

It gives that output:
```
python crackmapexec_bug.py -d adyolo -u user1 -p "yoloswag1!" 192.168.11.136 -s share --list encoding2
[*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:adyolo)
[+] 192.168.11.136:445 Login successful adyolo\user1:yoloswag1!
[+] 192.168.11.136:445 Contents of encoding2\*:
drw-rw-rw-       0 2015-11-01 22:50 .
drw-rw-rw-       0 2015-11-01 22:50 ..
-rw-rw-rw-      25 2015-11-01 22:32 credz.txt
-rw-rw-rw-      33 2015-11-01 13:14 àâæçéèêëïîôœ—– »« ”’€ÿüûù.txt
```

I saw you modified the `print_*` functions but I don't understand why utf-8 decoding fails at this point.

Finally, note that these encoding issues might exists for other features, every feature calling the `longname()` function.

Cheers.

**Comment by maaaaz** [comment] 2015-11-01 15:03
I'm also experiencing that bug, which is not directly related to encoding but only type:

```
$ python crackmapexec_bug.py -d adyolo -u administrator -p "<password>" 192.168.11.136 --sessions
[*] 192.168.11.136:445 is running Windows 6.3 Build 9600 (name:DC01) (domain:adyolo)
[+] 192.168.11.136:445 Login successful adyolo\administrator:<password>
[+] 192.168.11.136:445 DC01 Current active sessions:
sesi502_cltype_name 
Traceback (most recent call last):
  File "/root/venvcrackmapexec/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "crackmapexec_bug.py", line 2926, in connect
    print "{} {}".format(fname, yellow(session[fname]))
  File "crackmapexec_bug.py", line 87, in yellow
    return colored(text.decode('utf8'), 'yellow', attrs=['bold'])
AttributeError: 'int' object has no attribute 'decode'
<Greenlet at 0xb682bb6cL: connect('192.168.11.136')> failed with AttributeError
```

I was able to fix it by modifying the following line
from:
```
print "{} {}".format(fname, yellow(session[fname]))
```
to:
```
print "{} {}".format(fname, yellow(str(session[fname])))
```

**Comment by byt3bl33d3r** [comment] 2015-11-01 19:03
@maaaaz Awesome, This is a duplicate of #24 but wasn't able to reproduce since he/she didn't provide any info to reproduce. Will fix today

**Comment by byt3bl33d3r** [comment] 2015-11-01 19:15
@maaaaz Deleted the second comment and opened a new issue ticket here #34 since it was a seperate issue

**Comment by byt3bl33d3r** [comment] 2015-11-01 21:50
@maaaaz Should be fixed if not comment below. Thanks

**Closed by byt3bl33d3r** 2015-11-01 21:50 UTC
Labels: bug, duplicate

**Comment by maaaaz** [comment] 2015-11-02 19:49
Okay and I agree with you: double exception is really ugly :D 
For the [Windows version](https://github.com/maaaaz/CrackMapExecWin/blob/master/_src/crackmapexecwin.py) I used the following stuff:
* that for ignoring codepage issues on cmd term:
```
# Windows specific to output UTF-8
import codecs
codecs.register(lambda name: codecs.lookup('utf-8'))
```
* that to ignore potential decoding errors:
```
result.get_longname().encode('utf-8', 'ignore')
```

Anyway, I'll try your fix and let you know about it!
