### ISSUE TITLE
crash with cme smb shares

### ISSUE THREAD

**Issue by eroa** [byt3bl33d3r/CrackMapExec#253] opened 2018-06-21 10:03 UTC
## Steps to reproduce

1.install cme bleeding edge with virtualenv (pipenv install, pipenv shell, python setup.py install)

## Command string used

cme smb 192.168.XXX.XXXX --shares 

## CME verbose output (using the --verbose flag)

```
Traceback (most recent call last):
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 110, in __init__
    connection.__init__(self, args, db, host)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 41, in __init__
    self.proto_flow()
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/connection.py", line 70, in proto_flow
    self.enum_host_info()
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb.py", line 203, in enum_host_info
    self.conn.login('' , '')
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/smbconnection.py", line 258, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash, ntlmFallback)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/smb.py", line 3369, in login
    self.login_extended(user, password, domain, lmhash, nthash, use_ntlmv2 = True)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/smb.py", line 3235, in login_extended
    smb = self.recvSMB()
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/smb.py", line 2497, in recvSMB
    r = self._sess.recv_packet(self.__timeout)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/nmb.py", line 854, in recv_packet
    data = self.__read(timeout)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/nmb.py", line 932, in __read
    data = self.read_function(4, timeout)
  File "/home/toxic/.virtualenvs/CrackMapExec-KTynyVpX/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/thirdparty/impacket/impacket/nmb.py", line 921, in non_polling_read
    raise NetBIOSError, ('Error while reading from remote', ERRCLASS_OS, None)
NetBIOSError: Error while reading from remote
Thu Jun 21 11:42:23 2018 <Greenlet at 0x7f41e62fe690: smb(Namespace(clear_obfscripts=False, content=False, c, <protocol.database instance at 0x7f41eb11d050>, '192.168.100.6')> failed with NetBIOSError
```
## CME Version (cme --version)
4.0.1dev - Bug Pr0n

## OS
archlinux
## Target OS
win10
## Detailed issue explanation
cant use smb --shares, it's crash every times

**Comment by byt3bl33d3r** [comment] 2018-08-28 11:35
Have a feeling I'm not going to be able to reproduce this without more details on the environment and the target OS. If you can provide me with those details that would be awesome

**Comment by byt3bl33d3r** [comment] 2019-03-14 22:48
Closing since i don't have enough information to debug this.

**Closed by byt3bl33d3r** 2019-03-14 22:48 UTC
Labels: moar info required comrade

**Comment by eroa** [comment] 2019-04-15 21:13
sorry for the "necropost",  my envirronnement and OS are ArchLinux hardened, i3 , zsh ,
btw thank for you responsiveness
