### ISSUE TITLE
Unicode problems

### ISSUE THREAD

**Issue by zimzima** [byt3bl33d3r/CrackMapExec#228] opened 2018-01-12 15:49 UTC
## Steps to reproduce

1. Initiate share enumeration
2. cme crashes

## Command string used

cme smb [host] -u [user] -p [pass] --shares

## CME verbose output (using the --verbose flag)

DEBUG Calling shares()
SMB         x.x.x.x      445    [host]           [+] Enumerated shares
SMB         x.x.x.x      445    [host]           Share           Permissions     Remark
SMB         x.x.x.x      445    [host]           -----           -----------     ------
SMB         x.x.x.x      445    [host]           [-] Error enumerating shares: 'ascii' codec can't encode character u'\xe0' in position 15: ordinal not in range(128)

## CME Version (cme --version)

4.0.1dev - Bug Pr0n

## OS

Kali rolling

## Target OS

Windows 6.3 Build 9600 (from CME)

## Detailed issue explanation

Being in France, I have been having a lot if issues enumerating shares. I checked out the other issues on the subject and saw another user with the same problem, but unfortunately no solution!

The share enumeration seems to completely crash, and in the case of multiple targets it skips to the next one. Unfortunately it seems like the default share names in France cause this crash.

Anyway, thanks for this great tool! Good luck with the unicode bullshit :)

**Comment by its0x08** [comment] 2018-02-22 07:38
Its been more than a year that I ask for this fix and this guy hasn't done anything about it. Im in a LAN with at least 1800 devices connected and there are computer name/domain in almost every language .. and i cant test 90% of them because the tool crashes alot ... so CME is definitely useless.. 
-_-"

**Comment by asolino** [comment] 2018-02-22 15:05
> Its been more than a year that I ask for this fix and this guy hasn't done anything about it

Maybe *you* can do something about it instead of whining out loud at an open source collaborative project. Additions sent by the community is what makes these projects interesting, that's the reason why you have Pull Requests available. 
Did you test the latest release? Did you look at the code?  Did you spot the problem? Do you think you could find a solution for it so other non-american users would benefit too?

It's always funny to see some people requesting support on projects like this as if they were paid customers.

**Comment by CapitanShinChan** [comment] 2018-02-22 15:10
You know this is an open source project right? You can try to fix it by yourself.

This people just complaining without providing any type of solution fixes drive me crazy.

**Comment by its0x08** [comment] 2018-02-23 08:45
@asolino & @CapitanShinChan Guys im sorry to say but its obvious that you are big time noobs ... 
Besides that Im never that free to read the whole code so to implement unicode for everystring and test it and in case of any bug recheck the code to find the mistake and so on while the one that made the code really knows it and don need to spend time reading it all ... so dont blame people for not having enough time ;)
bye noobs .. 
get some books with logical problems and read it 3 times so u can understand way to solve problems...

**Comment by byt3bl33d3r** [comment] 2018-03-01 20:33
@zimzima This is a duplicate of #211. Unicode has always been an issue with CME, I'll try to fix these as best as I can when I get the time.

I'm locking this thread cause @its0x08 is an asshole, this is why we can't have nice things.

**Closed by byt3bl33d3r** 2018-03-01 20:33 UTC
