### ISSUE TITLE
OSX Bang Character Password  Error

### ISSUE THREAD

**Issue by Acid-J6** [byt3bl33d3r/CrackMapExec#242] opened 2018-04-18 23:08 UTC
## Steps to reproduce

1. cme smb -u test -p !123blarblar123! -d test <ip-Address> --pass-pol

## Command string used
!123blarblar123!

## CME verbose output (using the --verbose flag)
n/a as cme does not run due to the problem breaking it.

## CME Version (cme --version)
Version: 4.0.1dev

## OS
Darwin 17.5.0 Darwin Kernel Version 17.5.0

## Target OS
MacOS High Sierra 10.13.4

## Detailed issue explanation
When supplying a password which contains a Bang character ! the system tries to recall last executed command from bash_history.  So in the case above it tried to execute the first command in bash_history and as such stops CME.

**Comment by silverly** [comment] 2018-04-19 00:36
did you try placing the password in single quotes? alterative you can turn off bash history expansion with `set +o histexpand`

**Comment by Acid-J6** [comment] 2018-04-19 11:29
I tired with quotes and it does not process the request. I could turn bash history off which would make it work but just wanted to flag this.

**Comment by byt3bl33d3r** [comment] 2018-08-28 11:52
putting the password in single quotes worked for me on MacOS High Sierra on Iterm. Closing since i can't reproduce.

**Closed by byt3bl33d3r** 2018-08-28 11:52 UTC
