### ISSUE TITLE
pipenv: no se encontró la orden

### ISSUE THREAD

**Issue by gearcapitan** [byt3bl33d3r/CrackMapExec#215] opened 2017-10-28 22:57 UTC
## Steps to reproduce

![kali linux-2017-10-28-17-51-11 - copia](https://user-images.githubusercontent.com/13740942/32139267-6db677ec-bc09-11e7-8ca9-b9e8ea08e1d4.png)

## Command string used
┌─[root@Gear] - [~] - [sáb oct 28, 17:49]
└─[$] <> cd CrackMapExec && pipenv install
zsh: command not found: pipenv

root@Gear:~/CrackMapExec# pipenv install
bash: pipenv: no se encontró la orden

## OS
Linux Gear 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux

**Comment by byt3bl33d3r** [comment] 2017-11-04 10:48
Look like you missed an installation step. Closing.

**Closed by byt3bl33d3r** 2017-11-04 10:48 UTC

**Comment by c0d3xpl0it** [comment] 2018-01-01 16:24
@byt3bl33d3r This seems to be issue with New Kali 2017.3 vm-amd64. **Pipenv** is not found.

![image](https://user-images.githubusercontent.com/8144002/34469123-7ede51c4-ef31-11e7-95ca-2ac3537b0277.png)

**Comment by p0wner** [comment] 2018-02-02 14:24
I had the same issue with a fresh install of Kali 2017.3.
The problem is due to pipenv not being created inside the /usr/local/bin path.
Creating hard links solved the issue :
`ln -s ~/.local/bin/pipenv /usr/local/bin`
`ln -s ~/.local/bin/pew /usr/local/bin/pew`
