### ISSUE TITLE
No output from Win10 without internet?

### ISSUE THREAD

**Issue by jackassplus** [byt3bl33d3r/CrackMapExec#195] opened 2017-07-20 15:04 UTC
## Steps to reproduce
not really sure.

## Command string used
cme smb 192.168.32.9 --shares
cme smb 192.168.32.9 --shares -u user -p pass
cme smb 192.168.32.9 --sam -u user -p pass

## CME verbose output (using the --verbose flag)
DEBUG Passed args:
{'clear_obfscripts': False,
 'content': False,
 'cred_id': [],
 'darrell': False,
 'depth': None,
 'disks': False,
 'domain': None,
 'exclude_dirs': '',
 'exec_method': None,
 'execute': None,
 'fail_limit': None,
 'force_ps32': False,
 'gen_relay_list': None,
 'gfail_limit': None,
 'groups': None,
 'hash': [],
 'jitter': None,
 'list_modules': False,
 'local_auth': False,
 'local_groups': None,
 'loggedon_users': False,
 'lsa': False,
 'module': None,
 'module_options': [],
 'no_output': False,
 'ntds': None,
 'obfs': False,
 'only_files': False,
 'pass_pol': False,
 'password': [],
 'pattern': None,
 'port': 445,
 'protocol': 'smb',
 'ps_execute': None,
 'regex': None,
 'rid_brute': None,
 'sam': False,
 'server': 'https',
 'server_host': '0.0.0.0',
 'server_port': None,
 'sessions': False,
 'share': 'C$',
 'shares': True,
 'show_module_options': False,
 'spider': None,
 'spider_folder': '.',
 'target': ['192.168.32.9'],
 'threads': 100,
 'timeout': None,
 'ufail_limit': None,
 'username': [],
 'users': None,
 'verbose': True,
 'wmi': None,
 'wmi_namespace': 'root\\cimv2'}

## OS
Kali rolling and OSX

## Target OS
Windows 10 

## Detailed issue explanation
Windows 10 box (physical), no internet access (blanket block at firewall)
nothing else fancy.
Get no output of any kind, no errors, no warnings, just nothing.

Another Win10 (VM) with internet access seems to work fine.

**Comment by byt3bl33d3r** [comment] 2017-08-17 06:09
Well this is a new one, will see if i can reproduce

**Comment by jackassplus** [comment] 2017-08-17 13:53
I plan to decommission that box in a month or so (last physical windows box in the house) so let me know if you need anything else.

**Comment by byt3bl33d3r** [comment] 2017-10-25 04:21
tried reproducing this with no success. I'm going to close this since i feel like it was probably some configuration edge case with your system . Feel free to comment below if you have more info that i can use to reproduce.

Thanks

**Closed by byt3bl33d3r** 2017-10-25 04:21 UTC
Labels: unable to reproduce
