### ISSUE TITLE
OpenSSL Segmentation Fault when generating certificate

### ISSUE THREAD

**Issue by McZlatan-Bourne** [byt3bl33d3r/CrackMapExec#122] opened 2016-08-02 10:44 UTC
Segmentation fault on first time CME exec
O.S: Kali 2.*

![screenshot from 2016-08-02 11-37-52](https://cloud.githubusercontent.com/assets/8760121/17325939/38a0090a-58a6-11e6-8349-81435d422fc2.png)

**Comment by byt3bl33d3r** [comment] 2016-08-02 21:10
omg dat font.

Hmm it seems openssl is segfaulting when generating the certificate. 

Try running:
```bash
openssl req -new -x509 -keyout ~/.cme/cme.pem -out ~/.cme/cme.pem -days 365 -nodes -subj "/C=US"
```

**Comment by byt3bl33d3r** [comment] 2016-08-02 21:11
If that doesn't work, the openssl command utility is broken and you'll need to reinstall it

**Comment by byt3bl33d3r** [comment] 2016-08-08 16:32
@McZlatan-Bourne any update on this?

**Comment by McZlatan-Bourne** [comment] 2016-08-10 06:20
Sorry for the late response, i was hospitalized later on the day i asked the question.

I'm home now. 

I ran the command and generated the certificate successfully.

CME works now. THANKS!!!

![screenshot from 2016-08-10 07-14-23](https://cloud.githubusercontent.com/assets/8760121/17543759/cbb5d07e-5eca-11e6-9760-80f49a9e50c2.png)
![screenshot from 2016-08-10 07-12-31](https://cloud.githubusercontent.com/assets/8760121/17543758/cbb5de8e-5eca-11e6-841a-39bc1170b86a.png)

**Comment by McZlatan-Bourne** [comment] 2016-08-10 06:21
...and before i forget,

A gift from me to you friend.

*Hangyaboly
http://www.dafont.com/hangyaboly.font

**Comment by byt3bl33d3r** [comment] 2016-08-10 16:14
Lol thanks

I'm going to leave this open to remember to try and reproduce the segfault.

**Comment by byt3bl33d3r** [comment] 2016-09-21 15:28
Closing since I can't seem to reproduce this in anyway.

**Closed by byt3bl33d3r** 2016-09-21 15:28 UTC
Labels: bug, unable to reproduce

**Comment by SSHAD0w** [comment] 2020-11-25 01:20
I am experiencing the issue even after generating the new key.

**Comment by mpgn** [comment] 2020-11-25 08:14
If you are in kali: `apt install crackmapexec`

**Comment by samrays** [comment] 2020-12-29 10:41
> omg dat font.
> 
> Hmm it seems openssl is segfaulting when generating the certificate.
> 
> Try running:
> 
> ```shell
> openssl req -new -x509 -keyout ~/.cme/cme.pem -out ~/.cme/cme.pem -days 365 -nodes -subj "/C=US"
> ```

thanks, it fixed it.
