### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by AresS31** [byt3bl33d3r/CrackMapExec#158] opened 2017-02-23 14:43 UTC
## Command string used
cme 10.11.1.128 -u 'ares' -p 'ares' -x 'net users' --exec-method smbexec --verbose

## CME verbose output (using the --verbose flag)
DEBUG                                          {'domain': None, 'wdigest': None, 'verbose': True, 'sam': False, 'cred_id': [], 'module_options': [], 'fail_limit': None, 'share': 'C$', 'lusers': False, 'module': None, 'smb_port': 445, 'show_options': False, 'rid_brute': None, 'uac': False, 'ufail_limit': None, 'pass_pol': False, 'regex': None, 'list_modules': False, 'no_output': False, 'pattern': None, 'lsa': False, 'force_ps32': False, 'shares': False, 'content': False, 'server_host': '0.0.0.0', 'wmi': None, 'exclude_dirs': '', 'server_port': None, 'wmi_namespace': '//./root/cimv2', 'gfail_limit': None, 'mssql_query': None, 'username': ['ares'], 'hash': [], 'users': False, 'sessions': False, 'exec_method': 'smbexec', 'spider': None, 'ps_execute': None, 'threads': 100, 'mssql_port': 1433, 'password': ['ares'], 'mssql': False, 'mssql_auth': 'windows', 'ntds_pwdLastSet': False, 'execute': 'net users', 'target': ['10.11.1.128'], 'ntds_history': False, 'disks': False, 'ntds': None, 'server': 'https', 'depth': 10, 'local_auth': False, 'timeout': 20}
CME          10.11.1.128:445 DJ              [*] Windows 5.0 (name:DJ) (domain:DJ)
Traceback (most recent call last):
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/cme/connection.py", line 146, in __init__
    self.login()
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/cme/connection.py", line 411, in login
    if self.plaintext_login(self.domain, user, password): return
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/cme/connection.py", line 253, in plaintext_login
    self.db.add_credential('plaintext', domain, username, password)
  File "/root/.virtualenvs/CME/local/lib/python2.7/site-packages/cme/database.py", line 30, in add_credential
    cur.execute("INSERT INTO credentials (credtype, domain, username, password, pillagedfrom) VALUES (?,?,?,?,?)", [credtype, domain, username, password, pillaged_from] )
OperationalError: table credentials has no column named pillagedfrom
Thu Feb 23 14:42:14 2017 <Greenlet at 0x7fcfc4eeb370: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7fcfc4ca44, '10.11.1.128', None, None)> failed with OperationalError

[*] KTHXBYE!

## OS
uname -a
Linux phlegethon 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

## Target OS
meterpreter > sysinfo
Computer        : DJ
OS              : Windows 2000 (Build 2195).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x86/windows

**Comment by byt3bl33d3r** [comment] 2017-02-23 17:01
Duplicate of #146, I'll add a check for this in the new version.
Cheers

**Closed by byt3bl33d3r** 2017-02-23 17:01 UTC
