### ISSUE TITLE
Unhandled Exception - NetBIOSError

### ISSUE THREAD

**Issue by whoot** [byt3bl33d3r/CrackMapExec#161] opened 2017-03-22 07:35 UTC
# Command string used
```
crackmapexec 10.2.0.1/24 --shares -u (obfuscated) -p (obfuscated) -d (obfuscated)
```
# Error message 
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cme/connector.py", line 176, in connector
    ShareEnum(connection.conn, logger).enum()
  File "/usr/local/lib/python2.7/dist-packages/cme/enum/shares.py", line 16, in enum
    for share in self.smbconnection.listShares():
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 355, in listShares
    dce.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/transport.py", line 396, in connect
    self.__tid = self.__smb_connection.connectTree('IPC$')
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 332, in connectTree
    return self._SMBConnection.connect_tree(share)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2711, in tree_connect_andx
    smb = self.recvSMB()
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2473, in recvSMB
    r = self._sess.recv_packet(self.__timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 855, in recv_packet
    data = self.__read(timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 933, in __read
    data = self.read_function(4, timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 922, in non_polling_read
    raise NetBIOSError, ( 'Error while reading from remote', ERRCLASS_OS, None)
NetBIOSError: ('Error while reading from remote', 255, None)
<Greenlet at 0x7fbfa5b107d0: connector('10.2.0.234', Namespace(command=None, cred_id=[], depth=10, doma, <cme.database.CMEDatabase instance at 0x7fbfab3ce9, None, None, None)> failed with NetBIOSError
```
# OS
```
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.13-1kali3 (2017-03-13) x86_64 GNU/Linux
```
# Detailed issue explanation

It seems like this error is generated, if the share is not available. 
This are the last entries before the error:
```
03-22-2017 08:28:09 CME          10.2.0.234:445 NONE            [*] threadx (name:) (domain:WORKGROUP)
03-22-2017 08:28:10 CME          10.2.0.234:445 NONE            [-] (obfuscated)\(obfuscated):(obfuscated) STATUS_WAIT_2 
```

**Comment by byt3bl33d3r** [comment] 2017-04-07 05:20
duplicate of #157 , thanks for the report nevertheless

**Closed by byt3bl33d3r** 2017-04-07 05:20 UTC
Labels: duplicate
