### ISSUE TITLE
sys.excepthook is missing

### ISSUE THREAD

**Issue by voidnecron** [byt3bl33d3r/CrackMapExec#132] opened 2016-09-29 14:17 UTC
## Steps to reproduce
1. Fresh installed Kali 2016.2 amd64. Updated fully with apt-get update, upgrade, dist-upgrade.
2. Followed steps for installing via virtualenvwrapper
3. ???
4. Profit not so much, crashes out with:
   (CME) root@kali:~# crackmapexec 10.0.2.15
   09-29-2016 16:06:03 [_] First time use detected
   09-29-2016 16:06:03 [_] Creating home directory structure
   09-29-2016 16:06:03 [_] Initializing the database
   09-29-2016 16:06:03 [_] Copying default configuration file
   09-29-2016 16:06:03 [_] Generating SSL certificate
   09-29-2016 16:06:03 [_] KTHXBYE!
   Unhandled exception in thread started by 
   sys.excepthook is missing
   lost sys.stderr
   (CME) root@kali:~# crackmapexec 10.0.2.15
   09-29-2016 16:06:15 [_] KTHXBYE!
   Unhandled exception in thread started by 
   sys.excepthook is missing
   lost sys.stderr
   (CME) root@kali:~# crackmapexec 10.0.2.15 -u administrator -p Pa$$w0rd
   09-29-2016 16:06:45 [_] KTHXBYE!
   Unhandled exception in thread started by 
   sys.excepthook is missing
   lost sys.stderr
## Command string used

See above output
## CME verbose output (using the --verbose flag)

Even less output with verbose flag.
## OS

Kali 2016.2
## Target OS

Win7, Win10
## Detailed issue explanation

Not sure, I'm not a dev, mearly opssec curious.

**Comment by byt3bl33d3r** [comment] 2016-11-11 17:31
@voidnecron Sorry for the late response been busy :/
I've tried reproducing this with no success, what version of python are you using?

**Comment by byt3bl33d3r** [comment] 2016-11-11 17:40
just did some more digging and this actually seems to be a bug in Python itself 
http://bugs.python.org/issue11380
Did you ever get CME working and/or find a work around? really curious now lol
Thanks!

**Comment by byt3bl33d3r** [comment] 2017-04-07 05:11
Closing since I can't reproduce. Let me know if you encounter the same problem with v4.0

**Closed by byt3bl33d3r** 2017-04-07 05:11 UTC
Labels: unable to reproduce
