### ISSUE TITLE
DCERPCSessionError: TSCH SessionError: code: 0x80071a90 - ERROR_TRANSACTIONAL_CONFLICT

### ISSUE THREAD

**Issue by cclements** [byt3bl33d3r/CrackMapExec#149] opened 2017-01-10 21:52 UTC
Ran into this error a couple times during a mass mimikatz run.  Everything seems to be working properly despite the error.  I might have been too aggressive with the thread count at 200, but thought I'd let you know.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 167, in __init__
    module.on_admin_login(context, self)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/modules/mimikatz.py", line 50, in on_admin_login
    connection.execute(payload)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 39, in _decorator
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/connection.py", line 478, in execute
    output = u'{}'.format(exec_method.execute(payload, get_output).strip().decode('utf-8'))
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/execmethods/atexec.py", line 39, in execute
    self.doStuff(command)
  File "/usr/lib/python2.7/site-packages/crackmapexec-3.1.5.dev0-py2.7.egg/cme/execmethods/atexec.py", line 128, in doStuff
    tsch.hSchRpcDelete(dce, '\\%s' % tmpName)
  File "/usr/lib/python2.7/site-packages/impacket/dcerpc/v5/tsch.py", line 717, in hSchRpcDelete
    return dce.request(schRpcDelete)
  File "/usr/lib/python2.7/site-packages/impacket/dcerpc/v5/rpcrt.py", line 859, in request
    raise exception
DCERPCSessionError: TSCH SessionError: code: 0x80071a90 - ERROR_TRANSACTIONAL_CONFLICT - The function attempted to use a name that is reserved for use by another transaction.
Tue Jan 10 15:43:47 2017 <Greenlet at 0x7fa050635410: Connection(Namespace(content=False, cred_id=[], depth=10, dis, <cme.database.CMEDatabase instance at 0x7fa064166f, '192.168.40.149', <payload_module.CMEModule instance at 0x7fa06415bf, <CMEServer(Thread-1, started 140326819486128)>)> failed with DCERPCSessionError
```

**Comment by byt3bl33d3r** [comment] 2017-01-10 22:02
interesting, could you give me the full command you used?

**Comment by cclements** [comment] 2017-01-10 22:58
Nothing crazy:

cme -t 200 192.168.0.0/16 -u admin -p password -M mimikatz

**Comment by byt3bl33d3r** [comment] 2017-04-27 00:11
Closing since I haven't been able to reproduce this. Let me know if it comes up in the new version

**Closed by byt3bl33d3r** 2017-04-27 00:11 UTC
Labels: unable to reproduce
