### ISSUE TITLE
SMB Spider Regex Issue +  Fix

### ISSUE THREAD

**Issue by legleon** [byt3bl33d3r/CrackMapExec#302] opened 2019-04-03 13:13 UTC
Version: 4.0.1dev

-----------------------------------
Steps to reproduce
-----------------------------------
Run the regex spider against any share, the following error is produced:

  File "/usr/lib/python2.7/site-packages/crackmapexec-4.0.1.dev0-py2.7.egg/cme/protocols/smb/smbspider.py", line 101, in dir_list
    for pattern in self.pattern:
TypeError: 'NoneType' object is not iterable

-----------------------------------
Fix
-----------------------------------

Changes are made to the following file: 

cme/protocols/smb/smbspider.py

Line 104:
Change:
    for pattern in self.pattern:
To:
    if self.pattern is not None:
        for pattern in self.pattern:

Line 157
Change: 
     for pattern in self.pattern:
To:
    if self.pattern is not None: 
        for pattern in self.pattern:

**Comment by mpgn** [comment] 2020-04-22 14:16
Hello,

I'm closing since I cannot reproduce this problem. Try with cme v5 and feel free to re-open with more info.

**Closed by mpgn** 2020-04-22 14:16 UTC
